### PR TITLE
Clean whitespaces and suppress Gradle build warning

### PR DESCRIPTION
**Pull request by copycat-killer**

### CODE REVIEW

**Comment by jomifred** [comment]
Good!

which tool have you used to clean the spaces?
(I plan to include it as a gradle task)

**Comment by copycat-killer** [comment]
[git-remove-whitespaces](https://github.com/copycat-killer/dots/blob/master/bin/git-remove-whitespaces)

**Comment by jomifred** [comment]
When I run this script, it creates a new file with an “-e” suffix, should I rename all them manually?


> On 11 de ago de 2017, at 10:14, Luke Bonham <notifications@github.com> wrote:
> 
> git-remove-whitespaces
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by copycat-killer** [comment]
It shouldn't create no new file, maybe it's an env error. Try if the same happens giving the command directly:

```shell
git grep -I --name-only -z -e '' | xargs -0 sed -i -e 's/[ \t]\+\(\r\?\)$/\1/'
```

Or try setting `bash` env instead of `sh` in the script.

**Comment by jomifred** [comment]
it was a mac os issue. I tried on a linux machine and it works fine. thanks.

> On 11 de ago de 2017, at 17:02, Luke Bonham <notifications@github.com> wrote:
> 
> It shouldn't create no new file, maybe it's an env error. Try if the same happens giving the command directly:
> 
> git grep -I --name-only -z -e '' | xargs -0 sed -i -e 's/[ \t]\+\(\r\?\)$/\1/'
> Or try setting bash env instead of sh in the script.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Pull request merged**
